### ISSUE TITLE
Backslash is not escaped when converting dtb to dta

### ISSUE THREAD

**Issue by maxton** [mtolly/dtab#1]
Backslashes are not escaped when converting from binary to ASCII. This makes it impossible to do a round-trip ASCII to Binary for `ui/audition/gen/audition.dtb` in the TU5 patch.

To reproduce:
- create `test.dta` with the contents `"\\"`
- `dtab -b test.dta test.dtb`
- `dtab -a test.dtb test2.dta`
- `test2.dta` now contains `"\"`
- `dtab -b test2.dta test2.dtb` -> fails with non-obvious error "dtab.exe: Prelude.read: no parse"

**Comment by mtolly** [comment]
Thanks, fixed in v1.2. These are now the supported set of escape sequences:

  * `\q` means `"` inside a string, or `'` inside a quoted symbol
  * `\n` means newline in either a string or quoted symbol
  * `\\` means backslash in either a string or quoted symbol
